name: reusable-flake

on:
  workflow_call:
    inputs:
      binary-cache:
        required: false
        type: boolean
    secrets:
      ATTIC_ENDPOINT:
        required: false
      ATTIC_TOKEN:
        required: false
      ATTIC_CACHE:
        required: false

env:
  EXTRA_NIX_CONFIG: |
    extra-trusted-public-keys = public:AdkE6qSLmWKFX4AptLFl+n+RTPIo1lrBhT2sPgfg5s4=
    extra-substituters = https://cache.jzbor.de/public

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'
      - name: 'Download statix'
        run: nix build nixpkgs#statix --no-link
      - name: 'Run static checks'
        run: nix run nixpkgs#statix -- check .

  dead-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'
      - name: 'Download deadnix'
        run: nix build nixpkgs#deadnix --no-link
      - name: 'Run dead-code checks'
        run: nix run nixpkgs#deadnix -- -_ -f .

  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'
      - name: 'Run flake checks'
        run: nix flake check

  discover:
    runs-on: ubuntu-latest
    needs: [static-analysis, dead-code-analysis, flake-check]
    outputs:
      packages: ${{ steps.discover-step.outputs.packages }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'
      - name: 'Discover flake packages'
        id: discover-step
        run: printf "packages=%s\n" "$(nix eval .#packages.$(nix eval --impure --raw --expr 'builtins.currentSystem') --apply builtins.attrNames --json)" | tee -a $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [discover]
    if: ${{ needs.discover.outputs.packages != '' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.discover.outputs.packages) }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'
      - name: Install nix-fast-build
        run: nix build nixpkgs#nix-fast-build --no-link
      - name: 'Setup Attic cache'
        uses: ryanccn/attic-action@v0
        if: ${{ inputs.binary-cache == true }}
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: 'Build package "${{ matrix.package }}"'
        run: nix run nixpkgs#nix-fast-build -- --eval-workers 4 --eval-max-memory-size 3000 --skip-cached --no-nom --flake ".#packages.x86_64-linux.${{ matrix.package }}"


