name: reusable-flake

on:
  workflow_call:
    inputs:
      binary-cache:
        required: false
        type: boolean
      blocklist:
        required: false
        type: string
      magic-cache:
        required: false
        type: boolean
      upload-artifacts:
        required: false
        type: boolean
      architectures:
        required: false
        type: string
      build-args:
        required: false
        type: string
    secrets:
      ATTIC_ENDPOINT:
        required: false
      ATTIC_TOKEN:
        required: false
      ATTIC_CACHE:
        required: false

env:
  EXTRA_NIX_CONFIG: |
    extra-trusted-public-keys = public:AdkE6qSLmWKFX4AptLFl+n+RTPIo1lrBhT2sPgfg5s4=
    extra-substituters = https://cache.jzbor.de/public

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'

      - name: 'Download statix'
        run: nix build nixpkgs#statix --no-link

      - name: 'Run static checks'
        run: nix run nixpkgs#statix -- check


  dead-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'

      - name: 'Download deadnix'
        run: nix build nixpkgs#deadnix --no-link

      - name: 'Run dead-code checks'
        run: nix run nixpkgs#deadnix -- -_ -L -f .

  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'

      - name: 'Run flake checks'
        run: nix flake check


  discover:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.discover-step.outputs.packages }}
      native-arch: ${{ steps.native-architecture.outputs.native }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: '${{ env.EXTRA_NIX_CONFIG }}'

      - name: 'Setup Magic Nix Cache'
        if: ${{ inputs.magic-cache == true }}
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: 'Setup Attic cache'
        uses: ryanccn/attic-action@v0
        if: ${{ inputs.binary-cache == true }}
        with:
          skip-push: true
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: 'Get native architecture'
        id: native-architecture
        run: printf "native=%s\n" "$(nix eval --impure --raw --expr "builtins.toJSON [builtins.currentSystem]")" | tee -a $GITHUB_OUTPUT

      - name: 'Get architectures'
        id: get-architectures-step
        run: printf "architectures=%s\n" '${{ inputs.architectures || steps.native-architecture.outputs.native}}' | tee -a $GITHUB_OUTPUT

      - name: 'Get blocklist'
        id: get-blocklist
        run: printf "blocklist=%s\n" '${{ inputs.blocklist || '[]'}}' | tee -a $GITHUB_OUTPUT

      - name: 'Discover flake packages'
        id: discover-step
        run: >
          logfile="$(mktemp)";
          printf "packages=%s\n" "$(
            echo '${{ steps.get-architectures-step.outputs.architectures }}' | jq -r '.[]' | while read -r arch; do
                    nix eval ".#packages.$arch" --apply  "x: map(x: \"$arch.\" + x) (builtins.attrNames x)" --json --quiet 2>>$logfile;
            done | jq -sc 'reduce .[] as $x ([]; . + $x)' | jq -r '.[]' | while read -r pkg; do
                    if printf '${{ steps.get-blocklist.outputs.blocklist }}' | jq -r '.[]' | grep -x "$pkg" >/dev/null; then
                            echo "  [SKIPPED] $pkg" >/dev/stderr;
                            continue;
                    fi;
                    (
                      echo "Checking for $pkg in binary cache" >/dev/stderr;
                      if [ "${{ inputs.binary-cache }}" = "true" ] && curl -f "${{ secrets.ATTIC_ENDPOINT }}/${{ secrets.ATTIC_CACHE }}/$(nix eval --raw ".#packages.$pkg" 2>>$logfile | sed 's/.nix.store.\([a-z0-9]*\).*/\1/').narinfo" --netrc-file ${XDG_CONFIG_HOME:-$HOME/.config}/nix/netrc 1>/dev/null 2>&1; then
                              echo "  [FOUND]   $pkg" >/dev/stderr;
                      else
                              echo "  [MISSING] $pkg" >/dev/stderr;
                              echo "[\"$pkg\"]";
                      fi
                    ) &
            done | jq -sc 'reduce .[] as $x ([]; . + $x)'
          )" | tee -a $GITHUB_OUTPUT;
          printf "\n\nstderr:\n%s\n" "$(cat $logfile)"



  build:
    runs-on: ubuntu-latest
    needs: [discover, static-analysis, dead-code-analysis, flake-check]
    if: ${{ needs.discover.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.discover.outputs.packages) }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install QEMU/binfmt'
        if: ${{ inputs.architectures }}
        uses: docker/setup-qemu-action@v3

      - name: 'Determine package architecture'
        id: determine-architecture
        run: |
          printf 'arch=%s\n' "$(echo '${{ matrix.package }}' | cut -d. -f1)" | tee -a $GITHUB_OUTPUT

      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            ${{ env.EXTRA_NIX_CONFIG }}
            extra-platforms = ${{ steps.determine-architecture.outputs.arch }}

      - name: 'Setup Magic Nix Cache'
        if: ${{ inputs.magic-cache == true }}
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: 'Setup Attic cache'
        uses: ryanccn/attic-action@v0
        if: ${{ inputs.binary-cache == true }}
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: 'Build package "${{ matrix.package }}"'
        id: build-package
        run: |
          nix build ".#packages.${{ matrix.package }}" --no-link ${{ inputs.build-args }}
          printf "path=%s\n" "$(nix build ".#packages.${{ matrix.package }}" --print-out-paths --no-link | head -n1)" | tee -a $GITHUB_OUTPUT

      - name: 'Prepare package for upload as artifact'
        id: prepare-artifact
        if: ${{ inputs.upload-artifacts == true }}
        run: |
          cp -rvL "${{ steps.build-package.outputs.path }}" .
          printf "artifact_path=%s\n" "$(nix build ".#packages.${{ matrix.package }}" --print-out-paths --no-link | sed 's/\/nix\/store\/\(.*\)/\1/')" | tee -a $GITHUB_OUTPUT

      - name: 'Upload package as artifact'
        if: ${{ inputs.upload-artifacts == true }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: ${{ steps.prepare-artifact.outputs.artifact_path }}

      - name: 'Push package closure to binary cache'
        if: ${{ inputs.binary-cache == true }}
        run: attic push "${{ secrets.ATTIC_CACHE }}" "${{ steps.build-package.outputs.path }}"


